Controllers/PlaceController.cs
using Microsoft.AspNetCore.Mvc;
using GeoSearch.Models;
using GeoSearch.Data;
using GeoSearch.Services;

namespace GeoSearch.Controllers;

public class PlaceController : Controller
{
    private readonly ILogger<PlaceController> _logger;
    private readonly HttpClientHelper _httpClient;
    private readonly IConfiguration _configuration;

    private readonly string FoursquarePlaceDetailsApiUrl;
    private readonly string FoursquarePlaceImageApiUrl;
    private readonly string FoursquarePlaceTipsApiUrl;
    private readonly IFavoritesService _favoritesService;

    public PlaceController(ILogger<PlaceController> logger, HttpClientHelper httpClient, IFavoritesService FavoritesService, IConfiguration configuration)
    {
        _logger = logger;
        _httpClient = httpClient;
        _favoritesService = FavoritesService;
        _configuration = configuration;
        var baseUrl = _configuration.GetConnectionString("foursquare_apiurl");
        FoursquarePlaceDetailsApiUrl = baseUrl + "/{0}";
        FoursquarePlaceImageApiUrl = baseUrl + "/{0}/photos";
        FoursquarePlaceTipsApiUrl = baseUrl + "/{0}/tips";

    }

    [Route("Place/Details/{placeId}")]
    public async Task<ActionResult> Place(string placeId)
    {
        if (string.IsNullOrEmpty(placeId))
        {
            return RedirectToAction("Error");
        }
        
        var placeDetails = await GetPlaceDetailsFromApi(placeId);
        var placeTips = await GetPlaceTipsFromApi(placeId);
        var placeImages = await GetPlaceImagesFromApi(placeId);

        ViewBag.PlaceId = placeId;
        ViewBag.PlaceDetails = placeDetails;
        ViewBag.PlaceTips = placeTips;
        ViewBag.PlaceImages = placeImages;

        return View();
    }

    private async Task<FoursquarePlaceDetailsModel> GetPlaceDetailsFromApi(string placeId)
    {
        var formattedUrl = string.Format(FoursquarePlaceDetailsApiUrl, placeId);
        return await _httpClient.GetApiResponseAsync<FoursquarePlaceDetailsModel>(formattedUrl, _configuration.GetConnectionString("foursquare_apikey"));
    }

    private async Task<FoursquarePlaceTipsModel> GetPlaceTipsFromApi(string placeId)
    {
        var formattedUrl = string.Format(FoursquarePlaceTipsApiUrl, placeId);
        return new FoursquarePlaceTipsModel() {
            Tips = await _httpClient.GetApiResponseAsync<List<FoursquareTip>>(formattedUrl, _configuration.GetConnectionString("foursquare_apikey"))
        }; 
    }

    private async Task<FoursquarePlaceImagesModel> GetPlaceImagesFromApi(string placeId)
    {
        var formattedUrl = string.Format(FoursquarePlaceImageApiUrl, placeId);
        return new FoursquarePlaceImagesModel()
        {
            Images = await _httpClient.GetApiResponseAsync<List<PlaceImage>>(formattedUrl, _configuration.GetConnectionString("foursquare_apikey"))
        };
    }


    [Route("Place/Favorites")]
    public async Task<ActionResult> FavoritePlace()
    {
        var favoritePlaces = await _favoritesService.GetAllAsync();

        return View(favoritePlaces);
    }

    [HttpPost]
    public async Task<ActionResult> AddAsFavorite(FavoritePlace model)
    {
        if (model != null)
        {
            await _favoritesService.AddAsync(model);
        }

        return RedirectToAction("FavoritePlace");
    }

    [HttpPost]
    public async Task<ActionResult> RemoveFavorite(string fsqId)
    {
        if (!string.IsNullOrEmpty(fsqId))
        {
            await _favoritesService.DeleteAsync(fsqId);
        }

        return RedirectToAction("FavoritePlace");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeoSearch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeoSearch.styles.css" asp-append-version="true" />
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
            <span
              class="iconify"
              data-icon="ant-design:home-outlined"
              data-inline="false"
            ></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Place" asp-action="FavoritePlace">
            <span
              class="iconify"
              data-icon="clarity:favorite-line"
              data-inline="false"
            ></span>
          </a>
        </li>
        <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
            <span
              class="iconify"
              data-icon="eva:search-outline"
              data-inline="false"
            ></span>
          </a>
        </li>
      </ul>
    </nav>
    <main class="main">
        @RenderBody()
    </main>
  </body>
</html>

Views/Shared/_PlaceDetails.cshtml
@model GeoSearch.Models.FoursquarePlaceDetailsModel

@if (Model != null)
{
    <!-- Title -->
    @if (Model != null)
    {
        <div class="card border-success bg-success-custom">
            <div class="card-body d-flex align-items-center justify-content-center">
                <div style="display: flex; flex-direction:column; gap: 4px;">
                    <div style="display: flex; gap: 12px;">
                        <form asp-action="AddAsFavorite" method="post">
                            <input type="hidden" name="FsqId" value="@Model.Fsq_Id" />
                            <input type="hidden" name="Name" value="@Model.Name" />
                            @if (Model.Location != null)
                            {
                                <input type="hidden" name="Address" value="@Model.Location.Formatted_Address" />
                            }
                            <button type="submit" class="btn btn-link p-0 text-warning" style="border: none; background: none;">
                                <i class="fas fa-star fa-2x" id="favoriteIcon"></i>
                            </button>
                        </form>
                        <div>
                            <h3 style="margin:0;"><strong style="color:#23232e;">@Model.Name</strong></h3>
                            <i class="text-secondary">@Model.Timezone</i>
                        </div>
                    </div>
                    <div class="card-text">
                        @Model.Description
                    </div>
                </div>
            </div>
        </div>
    }

    <!-- Info -->
    <div class="card border-primary bg-primary-custom text-primary @(Model.Fax != null ? "tall" : "")">
        <div class="card-body">
            <h5 class="card-title">Contact</h5>
            <!-- Place Info -->
            @if (Model.Email != null)
            {
                <p><strong><i class="fas fa-envelope fa-lg card-icon bg-primary"></i></strong> @Model.Email</p>
            }
            @if (Model.Fax != null)
            {
                <p><strong><i class="fas fa-fax fa-lg card-icon bg-primary"></i></strong> @Model.Fax</p>
            }
            @if (Model.Tel != null)
            {
                <p><strong><i class="fas fa-phone fa-lg card-icon bg-primary"></i></strong> @Model.Tel</p>
            }
            @if (Model.Website != null)
            {
                <p><strong><i class="fas fa-globe fa-lg card-icon bg-primary"></i>
                    </strong> <a href="@Model.Website" target="_blank" class="card-link">@Model.Website</a>
                </p>
            }
            <!-- Location -->
            @if (Model != null && Model.Location != null)
            {
                <p><strong><i class="fas fa-map-pin fa-lg card-icon bg-primary"></i></strong> @Model.Location.Formatted_Address</p>
            }
            <!-- Verified -->
            <p><strong><i class="fas fa-check fa-lg card-icon bg-primary"></i></strong> Verified: @(Model.Verified ? "Yes" : "No")</p>
        </div>
    </div>

    <!-- Categories -->
    @if (Model != null && Model.Categories != null)
    {
        <div class="card border-danger bg-danger-custom text-danger">
            <div class="card-body">
                <h5 class="card-title">Categories</h5>
                @foreach (var category in Model.Categories)
                {
                    <div class="d-flex">
                        @if (category.Icon != null)
                        {
                            var iconUrl = $"{category.Icon.Prefix}32{category.Icon.Suffix}";
                            <img class="img-icon" src="@iconUrl" alt="@category.Name" style="margin-right: 10px;" />
                        }
                        <div class="d-flex flex-column">
                            <strong>@category.Short_Name</strong> 
                            <i>@category.Name</i>
                        </div>
                    </div>
                }
            </div>
        </div>
    }

    <!-- Hours -->
    @if (Model != null && Model.Hours != null)
    {
        <div class="card border-warning bg-warning-custom text-warning">
            <div class="card-body">
                <h5 class="card-title">Hours</h5>
                <p><strong>Is Local Holiday:</strong>
                    @if (Model.Hours.Is_Local_Holiday)
                    {
                        <i class="fas fa-check-circle fa-lg"></i>
                    }
                    else
                    {
                        <i class="fas fa-times-circle fa-lg"></i>
                    }
                </p>
                <p><strong>Open Now:</strong>
                    @if (Model.Hours.Open_Now)
                    {
                        <i class="fas fa-check-circle fa-lg"></i>
                    }
                    else
                    {
                        <i class="fas fa-times-circle fa-lg"></i>
                    }
                </p>
            </div>
        </div>
    }

    <!-- Stats -->
    @if (Model != null && Model.Stats != null)
    {
        <div class="card wide border-success bg-success-custom text-success">
            <div class="card-body">
                <h5 class="card-title">Stats</h5>
                    <div class="card-stat-container ">
                        <div class="card-stat">
                            <div class="stat-number bg-success"><strong>@Model.Stats.Total_Photos</strong></div>
                            <div><strong>Total Photos</strong></div>
                        </div>
                        <div class="card-stat">
                            <div class="stat-number bg-success"><strong>@Model.Stats.Total_Ratings</strong></div>
                            <div><strong>Total Ratings</strong></div>
                        </div>
                        <div class="card-stat">
                            <div class="stat-number bg-success"><strong>@Model.Stats.Total_Tips</strong></div>
                            <div><strong>Total Tips</strong></div>
                        </div>
                    </div>
            </div>
        </div>
    }

    <!-- Social Media -->
    @if (Model != null && Model.Social_Media != null)
    {
        <div class="card border-info bg-info-custom text-info">
            <div class="card-body">
                <h5 class="card-title">Social Media</h5>
                <p>
                    <strong><i class="fab fa-facebook fa-lg card-icon bg-info"></i></strong>
                    <a href="@($"https://facebook.com/{Model.Social_Media.Facebook_Id}")" target="_blank" class="card-link">
                        @Model.Social_Media.Facebook_Id
                    </a>
                </p>
                <p>
                    <strong><i class="fab fa-instagram fa-lg card-icon bg-info"></i></strong>
                    <a href="@($"https://instagram.com/{Model.Social_Media.Instagram}")" target="_blank" class="card-link">
                        @Model.Social_Media.Instagram
                    </a>
                </p>
                <p>
                    <strong><i class="fab fa-twitter fa-lg card-icon bg-info"></i></strong>
                    <a href="@($"https://twitter.com/{Model.Social_Media.Twitter}")" target="_blank" class="card-link">
                        @Model.Social_Media.Twitter
                    </a>
                </p>
                </div>
            </div>
    }
}
else
{
    <div class="card border-secondary bg-secondary-custom text-secondary">
        <div class="card-body">
            <p>No details found for this place.</p>
        </div>
    </div>
}

Views/Shared/_PlaceImages.cshtml
@model GeoSearch.Models.FoursquarePlaceImagesModel

@if (Model != null && Model.Images != null  && Model.Images.Count > 0)
{
    @foreach (var image in Model.Images)
    {
        <div class="card border-secondary bg-secondary-custom text-secondary tall">
            <div class="card-body" style="height: 100%">
                <h5 class="card-title"><i class="fas fa-camera"></i> Photo</h5>
                <div class=" d-flex flex-column justify-content-between" style="height: 90%">
                    <div style="width: 100%; height: @(@image.Tip == null ? "90%" : "50%")">
                        <img src="@($"{image.Prefix}250x250{image.Suffix}")" alt="@($"Image {@image.Id}")" class="image-card" />
                    </div>

                    <div>
                        @if (image != null && image.Tip != null)
                        {
                            @image.Tip.Text
                            <p><i class="fas fa-globe fa-lg"></i> <a href="@image.Tip.Url" target="_blank">@image.Tip.Url</a></p>
                        }

                        @if (image != null && image.Classifications != null && image.Classifications.Count > 0)
                        {
                            @foreach (var classification in image.Classifications)
                            {
                                <span class="badge bg-secondary">@classification</span>
                            }
                        }

                        @if (image != null)
                        {
                            <div style="display: flex; justify-content: space-between;">
                                <div>
                                    @if (image.Created_At != default(DateTime))
                                    {
                                        <i>@image.Created_At.ToString("MMMM dd, yyyy")</i>
                                    }
                                </div>
                                <div>
                                    <i class="fas fa-thumbs-up"></i> @(image.Tip != null ? @image.Tip.Agree_Count : "0")
                                    <i class="fas fa-thumbs-down"></i> @(image.Tip != null ? @image.Tip.Disagree_Count : "0")
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="card border-secondary bg-secondary-custom text-secondary">
        <div class="card-body">
            <p>No images found for this place.</p>
        </div>
    </div>
}

Views/Shared/_PlaceTips.cshtml
@model GeoSearch.Models.FoursquarePlaceTipsModel

@if (Model?.Tips != null && Model.Tips.Count > 0)
{
    @foreach (var tip in Model.Tips)
    {
        <div class="card border-warning bg-warning-custom text-warning @(tip.Photo != null ? "tall" : "")">
            <div class="card-body">
                <h5 class="card-title"><i class="fas fa-comment"></i> Tip</h5>
                @if (!string.IsNullOrEmpty(tip.Text))
                {
                    <p class="clamped-text scrollable-text">@tip.Text</p>
                }
                @if (tip.Photo != null)
                {
                    <img src="@($"{tip.Photo.Prefix}250x250{tip.Photo.Suffix}")" alt="@($"Image {@tip.Id}")" class="image-card" />
                }     
                <div style="display: flex; justify-content: space-between;">
                    <div>
                        @if (tip.CreatedAt != default(DateTime))
                        {
                            <i>@tip.CreatedAt.ToString("MMMM dd, yyyy")</i>
                        }
                    </div>
                    <div>
                        <i class="fas fa-thumbs-up"></i> @tip.Agree_Count
                        <i class="fas fa-thumbs-down"></i> @tip.Disagree_Count
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="card border-secondary bg-secondary-custom text-secondary">
        <div class="card-body">
            <p>No tips found for this place.</p>
        </div>
    </div>
}